import StreamChopper from '../stream-chopper.mjs';
import {createReadStream} from 'node:fs';

// Open a text file generated by this shell call:
// echo -e "Knock knock!\nNeutrino\nHow's there?" >joke.txt
const src = createReadStream('./joke.txt');

const chopper = new StreamChopper();

src.pipe(chopper);

// Read the first line. Outputs: "Knock knock!"
const firstLine = await chopper.readUntil('\n');
console.log(firstLine.toString());

// Skip the second line.
await chopper.seekUntil('\n');

// Read the third line. Outputs: "How's there?"
const thirdLine = await chopper.readUntil('\n');
console.log(thirdLine.toString());
